POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "kutta kamina",
    "number": 34983294
}

###
GET  http://localhost:3001/api/persons/

###
DELETE http://localhost:3001/api/persons/35